(()=>{'use strict';
 const asset=new URL('../../assets/',document.currentScript.src).href,root=document.getElementById('dashboard');if(!root)return;
 root.innerHTML=`<header class="dashboard-hero"><div class="hero-art"><div class="dashboard-robot" role="img" aria-label="피지컬 컴퓨팅 로봇"></div></div><div class="hero-title"><p class="curriculum">2022 개정 교육과정</p><h1>중학교 <span class="title-emphasis">피지컬 컴퓨팅</span></h1><p class="subtitle">센서와 액추에이터로 배우는 세상의 연결</p></div><div class="dashboard-tabs" role="tablist" aria-label="학습 종류"><button id="understandTab" data-unit="understand" role="tab" aria-controls="understandPanel" aria-selected="false"><span>Ⅰ</span><span>이해</span></button><button id="modulesTab" data-unit="modules" role="tab" aria-controls="modulePanel" aria-selected="true"><span>Ⅱ</span><span>설계</span></button><button id="projectsTab" data-unit="projects" role="tab" aria-controls="projectPanel" aria-selected="false"><span>Ⅲ</span><span>활용</span></button><button id="aiTab" data-unit="ai" role="tab" aria-controls="aiPanel" aria-selected="false"><span>Ⅳ</span><span>AI</span></button></div></header><p class="unit-description" aria-live="polite"></p><section id="modulePanel" role="tabpanel" aria-labelledby="modulesTab" class="device-panels"><section class="device-panel input-panel"><h2><svg class="role-icon" viewBox="0 0 64 40" aria-hidden="true"><path d="M3 20h29m-10-9 10 9-10 9"/><rect x="37" y="7" width="24" height="26" rx="5"/></svg>입력장치</h2><p class="panel-description">주변의 변화를 감지하여<br>정보를 입력하는 장치입니다.</p><div class="device-cards" data-group="input"></div></section><section class="device-panel output-panel"><h2><svg class="role-icon" viewBox="0 0 64 40" aria-hidden="true"><rect x="3" y="7" width="24" height="26" rx="5"/><path d="M32 20h29m-10-9 10 9-10 9"/></svg>출력장치</h2><p class="panel-description">입력된 정보를 바탕으로<br>결과를 표현하는 장치입니다.</p><div class="device-cards" data-group="output"></div></section></section><section id="projectPanel" role="tabpanel" aria-labelledby="projectsTab" class="application-panels" hidden><section class="device-panel assignment-panel"><h2>과제</h2><div class="application-cards" data-group="assignments"><button type="button" class="assignment-card" data-open-module="rotation-dc-motor"><strong class="assignment-title">다이얼 선풍기</strong><span class="assignment-devices">과제 : 가변저항 + DC모터</span><span class="card-arrow" aria-hidden="true">→</span></button></div></section><section class="device-panel group-project-panel"><h2>프로젝트</h2><div class="application-cards" data-group="group-projects"><p class="project-empty">모둠별 프로젝트 결과</p></div></section></section><section id="understandPanel" role="tabpanel" aria-labelledby="understandTab" class="empty-unit" hidden><h2>Ⅰ 이해</h2><p>준비 중</p></section><section id="aiPanel" role="tabpanel" aria-labelledby="aiTab" class="empty-unit" hidden><h2>Ⅳ AI</h2><p>준비 중</p></section>`;
 root.querySelector('.dashboard-robot').style.backgroundImage=`url('${asset}dashboard-robot-alpha.png')`;
 window.phycomDevices.forEach(d=>{const enabled=window.phycomNavigation.modules.some(m=>m.id===d.id&&m.enabled),card=document.createElement(enabled?'button':'article');card.className='device-card '+(enabled?'available':'preparing');if(enabled){card.type='button';card.dataset.openModule=d.id}else card.setAttribute('aria-disabled','true');
 const picture=document.createElement('div');picture.className='device-picture';if(d.image){const img=document.createElement('img');img.src=asset+d.image;img.alt=d.name;if(d.id==='dc-motor'||d.id==='servo-motor'){picture.classList.add('motor-card-crop');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',d.id==='dc-motor'?'0 0 1250 887':'0 100 970 800');svg.setAttribute('role','img');svg.setAttribute('aria-label',d.name);const image=document.createElementNS('http://www.w3.org/2000/svg','image');image.setAttribute('href',img.src);image.setAttribute('width',d.id==='dc-motor'?'1774':'1536');image.setAttribute('height',d.id==='dc-motor'?'887':'1024');svg.append(image);picture.append(svg)}else picture.append(img)}else{const image=document.createElement('span');image.setAttribute('role','img');image.setAttribute('aria-label',d.name);image.style.cssText=d.sprite.replace("assets/dashboard-reference.png",asset+'phyComDashBoard.png');picture.append(image)}card.append(picture);
 const title=document.createElement('h3');title.textContent=d.name;card.append(title);const text=document.createElement('p');text.textContent=d.description;card.append(text);const status=document.createElement('span');status.className='card-arrow';status.textContent='→';status.setAttribute('aria-hidden','true');card.append(status);root.querySelector(`[data-group="${d.group}"]`).append(card)});

 function activateTab(tab){const valid=['understand','modules','projects','ai'];if(!valid.includes(tab))tab='modules';root.dataset.activeUnit=tab;root.querySelector('.unit-description').textContent={understand:'피지컬 컴퓨팅의 개념과 작동 원리 알아보기',modules:'입력장치와 출력장치의 연결과 제어 방법 알아보기',projects:'입·출력장치를 활용하여 실생활 문제 해결하기',ai:'인공지능과 피지컬 컴퓨팅을 활용하여 문제 해결하기'}[tab];root.querySelectorAll('[data-unit]').forEach(b=>{const on=b.dataset.unit===tab;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;document.getElementById(b.getAttribute('aria-controls')).hidden=!on})}
 root.querySelectorAll('[data-unit]').forEach((b,i)=>{b.addEventListener('click',()=>activateTab(b.dataset.unit));b.addEventListener('keydown',e=>{const tabs=[...root.querySelectorAll('[data-unit]')];let n;if(e.key==='ArrowRight')n=(i+1)%4;else if(e.key==='ArrowLeft')n=(i+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();activateTab(tabs[n].dataset.unit);tabs[n].focus()})});
 function fitDashboard(){const scale=Math.min(innerWidth/1600,innerHeight/900);root.style.setProperty('--dashboard-scale',scale)}
 addEventListener('resize',fitDashboard);fitDashboard();activateTab('modules');window.studentDashboard={activateTab};
})();

