(()=>{'use strict';
 const asset=new URL('../../assets/',document.currentScript.src).href,root=document.getElementById('dashboard');if(!root)return;
 root.innerHTML=`<header class="dashboard-hero"><div><p>2022 개정 교육과정 · 중학교 정보</p><h1>피지컬 <span>컴퓨팅</span></h1><p>센서와 액추에이터로 세상을 움직여 보세요.</p></div><div class="dashboard-robot" role="img" aria-label="기존 피지컬 컴퓨팅 로봇"></div></header><div class="dashboard-tabs" role="tablist" aria-label="학습 종류"><button id="modulesTab" role="tab" aria-controls="modulePanel" aria-selected="true">모듈 학습</button><button id="projectsTab" role="tab" aria-controls="projectPanel" aria-selected="false">프로젝트</button></div><section id="modulePanel" role="tabpanel" aria-labelledby="modulesTab" class="device-panels"><section class="device-panel input-panel"><h2>입력장치 <small>세상을 감지해요</small></h2><div class="device-cards" data-group="input"></div></section><section class="device-panel output-panel"><h2>출력장치 <small>세상을 표현해요</small></h2><div class="device-cards" data-group="output"></div></section></section><section id="projectPanel" role="tabpanel" aria-labelledby="projectsTab" hidden><button class="project-card" data-open-module="rotation-dc-motor"><span class="project-badge">프로젝트 1</span><h2>가변저항으로 5단계 선풍기 만들기</h2><div class="project-card-flow"><img src="${asset}rotation-module.png" alt="가변저항"><span>→</span><div><b>단계</b><strong>0 · 1 · 2 · 3 · 4 · 5</strong></div><span>→</span><img src="${asset}DCmotor_fan_top.png" alt="선풍기"></div><p class="project-devices">가변저항 + DC모터</p><p>가변저항을 돌려 선풍기의 바람 세기를 조절해 봅시다.</p><span class="card-arrow">→</span></button></section>`;
 root.querySelector('.dashboard-robot').style.backgroundImage=`url('${asset}phyComDashBoard.png')`;
 window.phycomDevices.forEach(d=>{const enabled=window.phycomNavigation.modules.some(m=>m.id===d.id&&m.enabled),card=document.createElement(enabled?'button':'article');card.className='device-card '+(enabled?'available':'preparing');if(enabled){card.type='button';card.dataset.openModule=d.id}else card.setAttribute('aria-disabled','true');
 const picture=document.createElement('div');picture.className='device-picture';if(d.image){const img=document.createElement('img');img.src=asset+d.image;img.alt=d.name;picture.append(img)}else{const image=document.createElement('span');image.setAttribute('role','img');image.setAttribute('aria-label',d.name);image.style.cssText=d.sprite.replace("assets/dashboard-reference.png",asset+'phyComDashBoard.png');picture.append(image)}card.append(picture);
 const title=document.createElement('h3');title.textContent=d.name;card.append(title);const text=document.createElement('p');text.textContent=d.description;card.append(text);const status=document.createElement('span');status.className=enabled?'card-arrow':'preparing-badge';status.textContent=enabled?'→':'준비 중';card.append(status);root.querySelector(`[data-group="${d.group}"]`).append(card)});
 function activateTab(tab){const project=tab==='projects';document.getElementById('modulePanel').hidden=project;document.getElementById('projectPanel').hidden=!project;document.getElementById('modulesTab').setAttribute('aria-selected',!project);document.getElementById('projectsTab').setAttribute('aria-selected',project)}
 document.getElementById('modulesTab').addEventListener('click',()=>activateTab('modules'));document.getElementById('projectsTab').addEventListener('click',()=>activateTab('projects'));window.studentDashboard={activateTab};
})();
