(()=>{
const duties=[0,25,50,75,100];let index=0,currentDuty=0,timer=null;
function wave(duty){const x0=60,yHi=62,yLo=250,w=160,cycles=4;let d=duty===0?'M '+x0+' '+yLo:'M '+x0+' '+yHi;for(let i=0;i<cycles;i++){const x=x0+i*w,hi=w*duty/100;if(duty===0){d+=' L '+(x+w)+' '+yLo;continue}if(duty===100){d+=' L '+x+' '+yHi+' L '+(x+w)+' '+yHi;continue}d+=' L '+x+' '+yHi+' L '+(x+hi)+' '+yHi+' L '+(x+hi)+' '+yLo+' L '+(x+w)+' '+yLo;}return d;}
function ratio(d){if(d===0)return '계속 꺼짐';if(d===100)return '계속 켜짐';if(d%25!==0)return '켜져 있는 시간 '+d+'%';const g=(a,b)=>b?g(b,a%b):a,n=d/25,m=(100-d)/25,k=g(n,m);return '켜는 시간 '+(n/k)+' : 끄는 시간 '+(m/k);}
function render(d=currentDuty){currentDuty=d;const root=document.querySelector('.pwm-slide');if(!root)return;document.querySelector('#pwmDuty').textContent=d+'%';const entryValue=Math.round(d*255/100);const entryEl=document.querySelector('#pwmEntryValue');if(entryEl)entryEl.textContent=entryValue;document.querySelector('#pwmBrightness').textContent='밝기 약 '+d+'%';document.querySelector('#pwmRatio').textContent=ratio(d);document.querySelector('#pwmWave').setAttribute('d',wave(d));const glow=document.querySelector('#pwmGlow'),bulb=document.querySelector('#pwmBulb');glow.style.opacity=d/100;glow.style.transform='translate(-50%,-50%) scale('+(0.7+d/180)+')';bulb.style.filter='brightness('+(0.35+d/80)+') saturate('+(0.5+d/100)+')';document.querySelectorAll('[data-duty]').forEach(b=>b.classList.toggle('active',d%25===0&&+b.dataset.duty===d));}
function stop(){if(timer){clearInterval(timer);timer=null}const b=document.querySelector('#pwmPlay');if(b)b.textContent='▶ 자동 재생';}
function next(){stop();index=Math.min(duties.length-1,index+1);render(duties[index])}
function prev(){stop();index=Math.max(0,index-1);render(duties[index])}
function play(){if(timer){stop();return}currentDuty=0;index=0;render(0);document.querySelector('#pwmPlay').textContent='■ 멈추기';timer=setInterval(()=>{currentDuty=(currentDuty+1)%101;render(currentDuty);if(currentDuty%25===0)index=duties.indexOf(currentDuty)},35)}
function init(){const grid=document.querySelector('.pwm-grid');if(!grid)return;for(let i=0;i<=4;i++){const x=60+i*160;grid.insertAdjacentHTML('beforeend','<line x1="'+x+'" y1="35" x2="'+x+'" y2="260"/>')}document.querySelectorAll('[data-duty]').forEach(b=>b.onclick=()=>{stop();index=duties.indexOf(+b.dataset.duty);render(duties[index])});document.querySelector('#pwmPlay').onclick=play;render(0)}
window.pwmLesson={next,prev,play,stop,canNext:()=>index<duties.length-1,canPrev:()=>index>0,isAtMax:()=>index===duties.length-1,isPlaying:()=>timer!==null};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
